name: hacker_news_client
description: A client for the Hacker News API. Works on Flutter, Server, and Web.
version: 0.1.0
homepage: https://github.com/brianegan/hacker_news_client
author: Brian Egan <brian@brianegan.com>

dependencies:
  json_annotation: any
  http: any

dev_dependencies:
  build_runner: any
  json_serializable: any